services:
  sons-of-the-forest-server:
    image: ntavi/sotf-dedicated-arm64
    build: .
    ports:
      - "0.0.0.0:8766:8766/udp"
      - "0.0.0.0:27016:27016/udp"
      - "0.0.0.0:9700:9700/udp"
    volumes:
      - "./data:/server-data"
    tty: true
